# Add simulation data to CAMELS-DE

- create folder `timeseries_simulated`
- one .csv file per catchment
- build a file `CAMELS_DE_simulations.csv` with metadata about model runs for each catchment

In [11]:
import pandas as pd
import os
from glob import glob
from camelsp.util import INPUT_PATH

In [13]:
# get camels_ids from hydromet timeseries
camels_ids = [camels_id.split("_")[-1].split(".csv")[0] for camels_id in glob("../output_data/camels_de/timeseries/*.csv")]

# sort camels_ids
camels_ids = sorted(camels_ids)

print(f"Total number of stations in CAMELS-DE v1: {len(camels_ids)}")

Total number of stations in CAMELS-DE v1: 1555

## Create folder

In [3]:
os.makedirs("../output_data/camels_de/timeseries_simulated", exist_ok=True)

## Create .csv files with model results

columns:
* date
* pet_hargreaves [mm/day]
* discharge_vol_obs
* discharge_spec_obs [mm/day]
* discharge_spec_vol_lstm [mm/day]
* discharge_spec_sim_lstm [mm/day]
* discharge_vol_sim_hbv [mm/day]
* discharge_spec_sim_hbv [mm/day]
* simulation_period (training, validation, testing)

In [4]:
# read pickle files
lstm_data = pd.read_pickle(os.path.join(INPUT_PATH, "LSTM_CONCEPTUAL/Results_full_period/LSTM_full_range.pickle"))
conceptual_data = pd.read_pickle(os.path.join(INPUT_PATH, "LSTM_CONCEPTUAL/Results_full_period/HBV_full_range.pickle"))
pet_data = pd.read_pickle(os.path.join(INPUT_PATH, "LSTM_CONCEPTUAL/Results_full_period/pet_hargreaves.pickle"))

# simulation periods
training = ["1970-10-01", "1999-12-31"]
validation = ["1965-10-01", "1970-09-30"]
testing = ["2001-10-01", "2020-12-31"]

In [5]:
# read topographic attributes to calculate discharge_vol_sim
topographic_attributes = pd.read_csv("../output_data/camels_de/CAMELS_DE_topographic_attributes.csv", index_col=0)

for id in camels_ids:
    # get catchment area to calculate discharge_vol_sim from discharge_spec_sim
    area = topographic_attributes.loc[id, "area"] * 1e6  # km2 to m2

    # get lstm data
    if id in lstm_data.keys():
        df_lstm = lstm_data[id]

        # rename columns
        df_lstm = df_lstm.rename(columns={"y_sim": "discharge_spec_sim_lstm", "y_obs": "discharge_spec_obs"})

        # calculate discharge_vol_sim
        df_lstm["discharge_vol_sim_lstm"] = df_lstm["discharge_spec_sim_lstm"] * area / (24 * 3600) / 1000  # mm/day to m3/s

        # reorder columns
        df_lstm = df_lstm[["discharge_spec_obs", "discharge_vol_sim_lstm", "discharge_spec_sim_lstm"]]
    else:
        raise ValueError(f"ID {id} not found in LSTM data")
    

    # get conceptual data
    if id in conceptual_data.keys():
        df_conceptual = conceptual_data[id]

        # rename columns
        df_conceptual = df_conceptual.rename(columns={"y_sim": "discharge_spec_sim_hbv", "y_obs": "discharge_spec_obs"})

        # calculate discharge_vol_sim
        df_conceptual["discharge_vol_sim_hbv"] = df_conceptual["discharge_spec_sim_hbv"] * area / (24 * 3600) / 1000

        # reorder columns
        df_conceptual = df_conceptual[["discharge_spec_obs", "discharge_vol_sim_hbv", "discharge_spec_sim_hbv"]]
    else:
        # build a dataframe with the same structure as the lstm data and fill it with NaN
        df_conceptual = pd.DataFrame(index=df_lstm.index, columns=["discharge_spec_obs", "discharge_vol_sim_hbv", "discharge_spec_sim_hbv"])
        df_conceptual["discharge_spec_sim_hbv"] = float("nan")
        df_conceptual["discharge_vol_sim_hbv"] = float("nan")
        df_conceptual["discharge_spec_obs"] = df_lstm["discharge_spec_obs"]

    # get pet data
    if id in pet_data.keys():
        df_pet = pet_data[id]

        # rename columns
        df_pet = df_pet.rename(columns={"pet(mm/day)": "pet_hargreaves"})
    else:
        raise ValueError(f"ID {id} not found in PET data")

    # get discharge_vol_obs from hydromet_timeseries of the station
    df_discharge_obs = pd.read_csv(f"../output_data/camels_de/timeseries/CAMELS_DE_hydromet_timeseries_{id}.csv", index_col=0, parse_dates=True)["discharge_vol"]
    df_discharge_obs = df_discharge_obs.rename("discharge_vol_obs")

    # check that discharge_spec_obs are almost the same
    if (df_conceptual["discharge_spec_obs"] - df_lstm["discharge_spec_obs"] > 0.00001).any():
        raise ValueError(f"Discharge observations are not the same for ID {id}")

    # merge lstm and conceptual data, only keep one discharge_spec_obs column
    df = pd.concat([df_pet, df_discharge_obs, df_lstm, df_conceptual.drop(columns="discharge_spec_obs")], axis=1)

    # add simulation period flag
    df.loc[training[0]:training[1], "simulation_period"] = "training"
    df.loc[validation[0]:validation[1], "simulation_period"] = "validation"
    df.loc[testing[0]:testing[1], "simulation_period"] = "testing"

    # create the filename
    fname = f"../output_data/camels_de/timeseries_simulated/CAMELS_DE_discharge_sim_{id}.csv"

    # round to 2 decimal places
    df = df.round(2)

    # save to csv
    df.to_csv(fname, index=True, index_label="date")

## Create CAMELS_DE_simulations.csv

In [10]:
# dataframe to store results
df_results = pd.DataFrame(index=camels_ids)

### Count days of `discharge_spec` for each period

- training period: `01.10.1970` to `31.12.1999`
- validation period: `01.10.1965` to `30.09.1970`
- test period: `01.10.2001` to `31.12.2020`

In [12]:
# read the timeseries
for id in camels_ids:
    df = pd.read_csv(f"../output_data/camels_de/timeseries/CAMELS_DE_hydromet_timeseries_{id}.csv", index_col=0, parse_dates=True)

    # count number with discharge_spec that are not NaN for each period
    training_count = df.loc[training[0]:training[1], "discharge_spec"].count()
    validation_count = df.loc[validation[0]:validation[1], "discharge_spec"].count()
    testing_count = df.loc[testing[0]:testing[1], "discharge_spec"].count()

    # get ratio of stations with discharge_spec data for each period
    training_perc_complete = training_count / len(df.loc[training[0]:training[1], "discharge_spec"]) * 100 # in percent
    validation_perc_complete = validation_count / len(df.loc[validation[0]:validation[1], "discharge_spec"]) * 100 # in percent
    testing_perc_complete = testing_count / len(df.loc[testing[0]:testing[1], "discharge_spec"]) * 100 # in percent

    # store results
    df_results.loc[id, "training_perc_complete"] = round(training_perc_complete, 2)
    df_results.loc[id, "validation_perc_complete"] = round(validation_perc_complete, 2)
    df_results.loc[id, "testing_perc_complete"] = round(testing_perc_complete, 2)

df_results

,training_perc_complete,validation_perc_complete,testing_perc_complete
DE110000,99.71,81.71,100.00
DE110010,99.43,100.00,95.08
DE110020,100.00,100.00,100.00
DE110030,100.00,100.00,100.00
DE110040,100.00,100.00,100.00
...,...,...,...
DEG10580,100.00,100.00,100.00
DEG10590,100.00,100.00,100.00
DEG10600,100.00,100.00,100.00
DEG10610,100.00,100.00,100.00
DEG10620,100.00,100.00,96.83

### Add NSE per catchment
* lstm
* conceptual

In [13]:
df_nse_lstm = pd.read_csv(os.path.join(INPUT_PATH, "LSTM_CONCEPTUAL/NSE/LSTM_NSE.csv"))
df_nse_conceptual = pd.read_csv(os.path.join(INPUT_PATH, "LSTM_CONCEPTUAL/NSE/HBV_NSE.csv"))

# set index to basin_id
df_nse_lstm = df_nse_lstm.set_index("basin_id")
df_nse_conceptual = df_nse_conceptual.set_index("basin_id")

# rename columns
df_nse_lstm = df_nse_lstm.rename(columns={"NSE": "NSE_lstm"})
df_nse_conceptual = df_nse_conceptual.rename(columns={"NSE": "NSE_hbv"})

# join the two dataframes
df_results = df_results.join(df_nse_lstm)
df_results = df_results.join(df_nse_conceptual)

df_results

,training_perc_complete,validation_perc_complete,testing_perc_complete,NSE_lstm,NSE_conceptual
DE110000,99.71,81.71,100.00,0.931,0.819
DE110010,99.43,100.00,95.08,0.819,-0.026
DE110020,100.00,100.00,100.00,0.936,0.801
DE110030,100.00,100.00,100.00,0.913,0.777
DE110040,100.00,100.00,100.00,0.859,0.602
...,...,...,...,...,...
DEG10580,100.00,100.00,100.00,0.918,0.745
DEG10590,100.00,100.00,100.00,0.953,0.865
DEG10600,100.00,100.00,100.00,0.601,0.515
DEG10610,100.00,100.00,100.00,0.779,0.664
DEG10620,100.00,100.00,96.83,0.890,0.785

### Save csv

In [14]:
df_results.to_csv("../output_data/camels_de/CAMELS_DE_simulation_benchmark.csv", index_label="gauge_id")

## Add another .csv file for HBV model parameters

In [15]:
import pandas as pd
import os
from camelsp.util import INPUT_PATH

# dataframe to store results
df_hbv = pd.DataFrame(index=camels_ids)

# read the HBV parameters for all catchments
df_params = pd.read_csv(os.path.join(INPUT_PATH, "LSTM_CONCEPTUAL/HBV_model_parameters/HBV_dream_summary.csv"), index_col=0)
df_params

# drop columns NSE_training and NSE_testing
df_params = df_params.drop(columns=["NSE_training", "NSE_testing"])

# join the two dataframes
df_hbv = df_hbv.join(df_params)

df_hbv

,BETA,FC,K0,K1,K2,LP,PERC,UZL,TT,CFMAX,CFR,CWH,alpha,beta
DE110000,2.697174,405.46503,0.549201,0.230273,0.118831,0.886020,4.243058,4.272065,-0.493396,1.363465,0.021765,0.026129,2.674347,0.764425
DE110010,1.746806,346.64154,0.435103,0.297238,0.105281,0.256910,2.853093,7.994891,-0.894725,1.339450,0.047389,0.178345,2.804861,0.785600
DE110020,2.124430,351.52582,0.645256,0.192151,0.069511,0.495513,1.726985,10.203699,-0.321451,1.410346,0.034119,0.095558,2.326784,1.412284
DE110030,3.980955,541.63666,0.087823,0.283784,0.070148,0.810837,3.179504,42.019493,-0.055716,1.807845,0.047220,0.071675,2.808373,1.186264
DE110040,2.277487,518.99664,0.451634,0.319129,0.005614,0.797056,2.611371,85.643170,0.171584,2.293552,0.017765,0.044269,1.394605,1.656700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DEG10580,2.516212,389.99610,0.182572,0.485286,0.068055,0.875566,3.758904,16.161966,-0.067618,4.096061,0.069087,0.001509,2.841224,0.556975
DEG10590,4.257963,522.18400,0.425702,0.374030,0.041545,0.986410,1.780832,99.183880,0.245703,1.482583,0.034909,0.007453,1.551781,3.385839
DEG10600,5.916008,688.50130,0.787735,0.255607,0.039313,0.937546,1.891843,40.294888,0.635974,4.346504,0.034514,0.068602,2.681338,0.541412
DEG10610,5.823951,571.80540,0.809244,0.372895,0.107076,0.999674,0.628281,48.435640,0.204177,4.034543,0.007496,0.025049,0.887715,6.334758
DEG10620,3.970114,609.61255,0.303068,0.367505,0.053394,0.926281,2.471317,24.844688,-0.395654,2.946370,0.073305,0.139637,2.678919,0.579279

### Save csv

In [16]:
df_hbv.to_csv("../output_data/camels_de/CAMELS_DE_parameters_hbv.csv", index_label="gauge_id")